# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#  For correction purpose.
Ensure you always create new cell for your code, so that your answer won't override mine.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Create the following matrix:

In [14]:
np.linspace(0,1,50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [15]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [16]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [20]:
mat[2:5,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [6]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [22]:
mat[3,4]

20

In [8]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [27]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [10]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [30]:
np.arange(1,26).reshape(5,5).T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [11]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [31]:
mat[-1,1:]

array([22, 23, 24, 25])

### Now do the following

In [40]:
arr = np.random.randint(1,100,100)
arr

array([71, 25, 57, 71, 96, 50, 26, 78, 37, 29,  4, 27, 29, 96, 13, 84, 88,
       23, 10, 14, 72, 90, 79, 73, 21, 95, 55, 42, 66, 66, 74, 17,  6, 67,
       98, 88, 47, 75, 31,  3, 89, 40, 54, 97, 67, 11,  2, 13, 54, 72, 89,
       95, 74, 92, 92, 94, 90, 39, 96, 66, 26, 15, 93, 10, 49, 19, 16, 75,
       34, 65, 30, 27, 88, 17, 28, 96, 59, 41,  6, 49, 50, 26, 76, 48, 23,
       21, 86, 75, 58, 91, 15, 67, 55, 16, 31, 28, 96, 12, 33, 18])

#### Get all the element greater than 80 in the array (arr) above

In [41]:
arr[arr>80]

array([96, 96, 84, 88, 90, 95, 98, 88, 89, 97, 89, 95, 92, 92, 94, 90, 96,
       93, 88, 96, 86, 91, 96])

#### return all values that are even number and greater than 50

In [42]:
arr[(arr>50) & (arr%2==0)]

array([96, 78, 96, 84, 88, 72, 90, 66, 66, 74, 98, 88, 54, 54, 72, 74, 92,
       92, 94, 90, 96, 66, 88, 96, 76, 86, 58, 96])

####  change the shape of the array to 10x10 matrix

In [43]:
arr.reshape(10,10)

array([[71, 25, 57, 71, 96, 50, 26, 78, 37, 29],
       [ 4, 27, 29, 96, 13, 84, 88, 23, 10, 14],
       [72, 90, 79, 73, 21, 95, 55, 42, 66, 66],
       [74, 17,  6, 67, 98, 88, 47, 75, 31,  3],
       [89, 40, 54, 97, 67, 11,  2, 13, 54, 72],
       [89, 95, 74, 92, 92, 94, 90, 39, 96, 66],
       [26, 15, 93, 10, 49, 19, 16, 75, 34, 65],
       [30, 27, 88, 17, 28, 96, 59, 41,  6, 49],
       [50, 26, 76, 48, 23, 21, 86, 75, 58, 91],
       [15, 67, 55, 16, 31, 28, 96, 12, 33, 18]])

#### what is the minimum value of the array arr?

In [44]:
arr.min()

2

#### what is the index of te minimum value of the array arr?

In [45]:
arr.argmin()

46

#### what is the maximum value of the array arr?

In [46]:
arr.max()

98

#### what is the index of te minimum value of the array arr?

In [47]:
arr.argmax()

34

# Great Job!