In [1]:
import numpy as np

## SOLVING DETERMINANT OF A GIVEN (n x n) MATRICES 

In [3]:
def getMatrix():
    try:
        print("DETERMINANT CALCULATOR")
        mat = []
        rows = int(input("Enter the number of rows: "))
        cols = int(input("Enter the number of cols: "))
        if rows != cols:
            print("Number of columns must be equal to Number of rows")
        else:

            for row in range(rows):
                mat.append([])
                values = input("Enter values for row {} seperated by comma (,) :  ".format(row)).split(',')
                if len(values) == cols:
                    for i in values:
                        mat[row].append(int(i))
                else:
                    print("Column doesn't match")
                    break
    except ValueError as err:
        print(err)
    except:
        print('An error occured')
        
    return mat

def main():
    try:
        matrix = getMatrix()
        if len(matrix) !=0:
            matrix = np.array(matrix)
            determinant = np.linalg.det(matrix)
            print()
            print(f"The determinant of \n {matrix} is ",end=' ')
            return determinant
    except:
        print("An error occured")
if __name__ == '__main__':
    print(main())


DETERMINANT CALCULATOR
Enter the number of rows: 2
Enter the number of cols: 2
Enter values for row 0 seperated by comma (,) :  2,2
Enter values for row 1 seperated by comma (,) :  2,2

The determinant of 
 [[2 2]
 [2 2]] is  0.0


# SYSTEM OF LINEAR EQUATION
suppose we<br> x + y + z = 19 <br>
           2x + 4y   = 2 <br>
           3x + 9y -3z = 4 <br>
 To solve the equation above we have to transform it to matrices.<br>
 By doing this we will have<br>
<b>Matrix A</b><br>[ [ 1, 1, 1 ]<br>
                  [ 2, 4, 0 ]<br>
                  [ 3, 9, -3 ] ]<br>
and a column<b> Vector B </b><br>
[ [ 19 ]<br>
[ 2 ]<br>
[ 4 ] ]<br>

We then compute the <b>unknown</b><br>[x,y,z]<br>
X = A(^-1)B

## The steps followed:
1. Get all values for <b>matrix A</b><br>
2. Then get all values for <b>column vector B</b> corresponding to each row in matrix A.<br>
3. Then solve by leveraging on numpy ability.<br>

In [3]:

def getMatrixA():
    try:
        print("==============================WElCOME TO SYSTEM OF LINEAR EQUATION.=========================")        
        mat = []
        rows = int(input("How many unknowns : "))
        cols = rows
        print("GETTING VALUES FOR MATRIX A ")
        for row in range(rows):
            mat.append([])
            values = input("Enter values for row {} seperated by comma (,) :  ".format(row)).split(',')
            if len(values) == cols:
                for i in values:
                    mat[row].append(int(i))
            else:
                print("Column doesn't match")
                break
    except ValueError as err:
        print(err)
        
    return mat

matrixA = getMatrixA() 
n = len(matrixA)

def getVectorB():
    try:
        matB = []
        for i in range(1,n+1):
            value = eval(input("Enter value for row {}, of the column vector:".format(i)))
            matB.append(value)
        return matB
    except ValueError as err:
        print(err)

matrixB = getVectorB()

A = np.asarray(matrixA) 
B = np.asarray(matrixB).reshape(n,1)

if np.linalg.det(A) == 0:
    print("Cannot compute solution for singular matrix")

else:

    A_inv = np.linalg.inv(A)


    X = np.linalg.solve(A_inv,B)

    print('A = \n', A)
    print('B = \n', B)


    print("The solution for the  equation is: \n",X)




==============================WElCOME TO SYSTEM OF LINEAR EQUATION.=========================
How many unknowns : 3
GETTING VALUES FOR MATRIX A 
Enter values for row 0 seperated by comma (,) :  1,1,1
Enter values for row 1 seperated by comma (,) :  2,4,0
Enter values for row 2 seperated by comma (,) :  3,9,-3
Enter value for row 1, of the column vector:19
Enter value for row 2, of the column vector:2
Enter value for row 3, of the column vector:4
Cannot compute solution for singular matrix


### HERE IS ANOTHER FORMAT...... without handling exceptions.

In [4]:
import numpy as  np

def getMatrix_A():
    print("WELCOME TO SYSTEM OF LINEAR EQUATION")
    matA = []
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of cols: "))
    if rows != cols:
        print("Number of columns must be equal to Number of rows")
    else:

        for row in range(rows):
            matA.append([])
            for col in range(cols):
                value = eval(input("Enter value for row {}, column {} of the matrix: ".format(row,col)))
                matA[row].append(value)
    return matA

matrixA = getMatrix_A()  
n = len(matrixA)


def getVector_B():
    matB = []
    for i in range(1,n+1):
        value = eval(input("Enter value for row {}, of the column vector:".format(i)))
        matB.append(value)
    return matB

      
matrixB = getVector_B()

   
A = np.asarray(matrixA) 
B = np.asarray(matrixB).reshape(n,1)

A_inv = np.linalg.inv(A)


X = np.linalg.solve(A_inv,B)

det = np.linalg.det(A)



print('A = \n', A)
print('B = \n', B)


print("The solution for the  equation is: \n",X)



WELCOME TO SYSTEM OF LINEAR EQUATION
Enter the number of rows: 2
Enter the number of cols: 2
Enter value for row 0, column 0 of the matrix: 3
Enter value for row 0, column 1 of the matrix: 4
Enter value for row 1, column 0 of the matrix: 2
Enter value for row 1, column 1 of the matrix: -6
Enter value for row 1, of the column vector:3
Enter value for row 2, of the column vector:4
A = 
 [[ 3  4]
 [ 2 -6]]
B = 
 [[3]
 [4]]
The solution for the  equation is: 
 [[ 25.]
 [-18.]]
